### PR TITLE
Add Turbo Mode

### PR DESCRIPTION
**Pull request by trbocode**
Might need some changes to compilation to pass timing checks

### CODE REVIEW

**Comment by sorgelig** [comment]
I doubt it will work reliably, especially with SDRAM fetches.

**Comment by trbocode** [comment]
It works on Metal Slug, other games have Corrupted Graphics.

**Comment by Koston-0xDEADBEEF** [comment]
> It works on Metal Slug, other games have Corrupted Graphics.
> 
> EDIT: Which is Supposedly true to hardware.

Correct. I have modified a few of my MVS boards with overclock switches, feeding CPU from a different crystal. 18MHz is highest that is perfectly stable; 24MHz is unusable.

This is only helpful for Metal Slug games, others get graphics errors. It is especially useful for making Metal Slug 2 enjoyable, from worst to best game in series after overclocking.

Universe BIOS 4.0 has also been specifically patched to accommodate overclocked boards, it has no graphics glitches and detects overclocking (although it can't distinguish between 16MHz and 18MHz, as former used to be the common one).

I suggest you add both CPU speed 18MHz and 24MHz options to allow staying within original hardware capabilities. And rename it from turbo to overclock to avoid name overlap confusion with Metal Slug 2 Turbo romhack which only fixes a bug in the game engine, reducing slowdown a lot.

Thank you for consideration. For me, this is an important feature, my favourite game on the system depends on it!

**Comment by trbocode** [comment]
I rebased this on the new version and it seems to be slightly buggier(?, might be due to core) - Since the new version includes 48M clocks, it made it a bit simpler.

**Pull request closed without merging**
