### PR TITLE
ADPCM fix, ROMWAIT

### PR DESCRIPTION
**Pull request by paulb-nl**
ADPCM fix for missing sample in Last Blade 2

Set ROMWAIT from xml. Fixes glitches in some screens in Ninja Commando. Needs update to Main

### CODE REVIEW

**Comment by sorgelig** [comment]
Is it something exists on real HW? Why cannot add wait signal permanently with fixed delay?

**Comment by paulb-nl** [comment]
The ROMWAIT and PWAIT signals come from the cartridge pcb so the cartridge decides if the wait cycles are needed. 

I have only found 2 cartridges with ROMWAIT set: Blue's Journey and Ninja Commando. Here is an example: 
https://www.mvs-scans.com/images/3/38/Ninja_commando_set1_b1_front.jpg
Look for "1 WAIT" jumper

All other games don't need these wait cycles.

For .neo format I have added it to NeoQuirks in Main so it works properly too.

**Comment by sorgelig** [comment]
i see.

**Comment by sorgelig** [comment]
Make a PR in Main then too.

**Comment by mario-64** [comment]
> The ROMWAIT and PWAIT signals come from the cartridge pcb so the cartridge decides if the wait cycles are needed.
> 
> I have only found 2 cartridges with ROMWAIT set: Blue's Journey and Ninja Commando. Here is an example: https://www.mvs-scans.com/images/3/38/Ninja_commando_set1_b1_front.jpg Look for "1 WAIT" jumper
> 
> All other games don't need these wait cycles.
> 
> For .neo format I have added it to NeoQuirks in Main so it works properly too.

I’m not familiar with NeoQuirks. Does this mean if using .neo format these fixes are baked into Main? No need to edit any files?

**Comment by sorgelig** [comment]
> I’m not familiar with NeoQuirks. Does this mean if using .neo format these fixes are baked into Main? No need to edit any files?

right.

**Pull request merged**
