### PR TITLE
Prevent interpolator from continually stepping past target

### PR DESCRIPTION
**Pull request by greyrogue**

### CODE REVIEW

**Comment by jotego** [comment]
@greyrogue did you actually see the issue in simulation?

**Comment by greyrogue** [comment]
Shock Troopers sets the deltan registers to 0 (pauses or silences the channel) during the attract mode. It causes a loud buzzing as no additional adv signals are generated and the last step is continually added. If I understand the code correctly, it wouldn't work if deltan is smaller than ~0x100.

**Comment by jotego** [comment]
I think it makes sense, but let me simulate it.

**Comment by greyrogue** [comment]
The logic misses one equal case (pcminter== pcmlast && step_sign ==0).  It should probably be this instead:
    else pcminter <= ( (pcminter < pcmlast) && ~step_sign ) ? pcminter + step: ( (pcminter > pcmlast) && step_sign ) ? pcminter - step : pcminter;

**Pull request merged**
